# Generated by Django 5.0.6 on 2024-05-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('c', 'client'), ('f', 'freelancer')], default='c', max_length=50),
        ),
    ]
