# Generated by Django 5.0.6 on 2024-05-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_account_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='skills',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('c', 'client'), ('f', 'freelancer')], default='f', max_length=50),
        ),
    ]
