# Generated by Django 5.0.6 on 2024-05-11 18:25

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_posting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='description',
            new_name='abstract',
        ),
        migrations.AddField(
            model_name='posting',
            name='detail_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=home.models.get_post_image_filepath),
        ),
    ]
